### ISSUE TITLE
要件定義

### ISSUE THREAD

**Issue by IshimotoTakara** [Takara-hub/kyutech_db#1]
要件定義とは、クライアントの要望と、その要望をどのように叶えるのかを文章としてまとめたものです。
成果物は、「システム」、「機能要件」、「非機能要件」に関する詳細を記入した要件定義書です。
要件定義書は、「専門知識がなくても内容が分かる」、「問題の解決策が記載されている」ことを意識して作成する必要があります。
今回は「九工大の情報集める」をテーマに問題の分析と解決策の検討をしていく。

**Comment by takemotomizuki** [comment]
企画書：<https://github.com/Takara-hub/kyutech_db/wiki/%E4%BC%81%E7%94%BB%E6%9B%B8>

**Comment by IshimotoTakara** [comment]
システムの基本設計、詳細設計で作る図（画面遷移図、ER図など）はリアルタイムで同時編集できる[Figma](https://www.figma.com/)とかを使うといいのかな？

**Comment by IshimotoTakara** [comment]
[在校生向けアプリ](https://moduleapps.com/mobile-marketing/13697app/#zai_xiao_sheng_xiangke_da_xueapuri)はいろんなところやってるから参考にできるね！
[九大アプリ](https://prtimes.jp/main/html/rd/p/000000001.000099455.html)

**Comment by takemotomizuki** [comment]
> システムの基本設計、詳細設計で作る図（画面遷移図、ER図など）はリアルタイムで同時編集できる[Figma](https://www.figma.com/)とかを使うといいのかな？

figmaはDentalightの子が使ってるけどもろデザインって感じだね
結局ライブラリ依存だから大まかな配置と機能を決めるのだったらfigmaでもいいと思う

ER図はそもそもNoSQL使う可能性もあるから要検討って感じかな

**Comment by takemotomizuki** [comment]
デジタルデジタル学生証使うところないのクソおもろい
![image](https://user-images.githubusercontent.com/82038430/172087203-7b6ef3e1-7a64-49b8-a3fc-1252fd7639d8.png)

**Comment by IshimotoTakara** [comment]
> figmaはDentalightの子が使ってるけどもろデザインって感じだね

FigmaはUI/UXメインだね！👌
ER図とか機能リストなどは開発進めながらでいいと思う！（Wikiに付け足していこうか👍）
なんか設計しっかりやってると、無駄なくなるしちゃんとやってる感出てすき笑

**Comment by IshimotoTakara** [comment]
WikiにまとめていけばOKてことでClose
